# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('fechaDesde', models.DateField(default=datetime.datetime(2017, 3, 20, 15, 59, 33, 797092), verbose_name='Fecha desde')),
                ('enCurso', models.BooleanField(default=False, verbose_name='En curso')),
                ('fechaHasta', models.DateField(blank=True, default=datetime.datetime(2017, 3, 20, 15, 59, 33, 797248), null=True, verbose_name='Fecha hasta')),
                ('modalidad', models.IntegerField(choices=[(0, 'Full Time'), (1, 'Freelance')], default=0, verbose_name='Modalidad')),
                ('img', models.ImageField(upload_to='proyectos/', verbose_name='Imagen')),
                ('empresas', models.ManyToManyField(to='curriculum.Empresa', verbose_name='Empresas')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Idioma', verbose_name='Idioma')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Pais', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='TareaProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('areas', models.ManyToManyField(blank=True, to='curriculum.AreaTecnica', verbose_name='Areas')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.TipoProyecto', verbose_name='Tipo de proyecto'),
        ),
    ]
