# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaDesde',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha desde'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaHasta',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha hasta'),
        ),
    ]
